version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    platform: linux/amd64
    image: franciscpd/node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    volumes:
      - node-app:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    platform: linux/amd64
    build: 
      context: nginx
    container_name: nginx
    image: franciscpd/nginx-node
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  node-app: